### PR TITLE
Use native node test runner, added code coverage support, removed grunt

### PR DESCRIPTION
**Pull request by hulkish**
This PR does not alter any published code, only modifies `devDependencies`, tests & dev tooling. In detail:

- converted tests to use native node test runner
- removed grunt, mocha, chai & sinon
- added code coverage support using [`c8`](https://github.com/bcoe/c8) (since this is not yet supported natively in node)
  - i put line code coverage requirement to  87% - which is the current line coverage of `lib/**/*.js`. 

Some things to note:

- requires `node` to be >= 18. Preferably >= 20, whereas the test runner was considered stable.
- if you decide to run test directly via `node --test <test files>` (as opposed to `npm run test`), it's important to note that you will likely need to use `--test-concurrency=1` as many of the tests use `createServer()` from `http`/`https`/`net` and will therefore have dangling handle conflicts if ran concurrently. 
- If you're running.a single test file or multiple files where this is not the case, you can safely exclude `--test-concurrency=1`
- In a separate PR, i recommend sticking to a single test file naming convention: `foo.test.js`. Currently this repo seems to use 2 different naming conventions for test files: `foo-test.js` & `foo.test.js` for seemingly no reason. For brevity, I chose not to make this change in this PR.

### CODE REVIEW

**Comment by hulkish** [comment]
Hmm, looks like failing because glob patterns for tests are only available in node 21+, I guess I could remove the quotes to rely on shell glob expansion

**Comment by andris9** [comment]
Thank you for the effort but these tests do not seem to pass. npm test should work at least both with node 18 and 20. Currently, it partially works with 21 only.

**Comment by hulkish** [comment]
> Thank you for the effort but these tests do not seem to pass. npm test should work at least both with node 18 and 20. Currently, it partially works with 21 only.

hmm, looks like the jobs for 18 & 20 were cancelled... I updated the scripts to use shell globs - looks like the tests would have passed if not cancelled

**Comment by andris9** [comment]
Did you try to run tests locally under node 18 and 20? It doesn’t work.

**Comment by andris9** [comment]
Btw, if you want to modify the test matrix, you can do so here: https://github.com/nodemailer/nodemailer/blob/4233f6f89e5d432ade6b6d3e5c578996ddeb831e/.github/workflows/test.yml#L11

In general, it seems a great idea to move from Grunt to node native test runner but the tests must pass on max supported platforms. In this case on Node 18, 20, 21

**Comment by hulkish** [comment]
> Did you try to run tests locally under node 18 and 20? It doesn’t work.

I just ran the tests on `node@18.19.0` and `node@20.10.0` and everything passed.

**Comment by hulkish** [comment]
> Btw, if you want to modify the test matrix, you can do so here:
> 
> https://github.com/nodemailer/nodemailer/blob/4233f6f89e5d432ade6b6d3e5c578996ddeb831e/.github/workflows/test.yml#L11
> 
> In general, it seems a great idea to move from Grunt to node native test runner but the tests must pass on max supported platforms. In this case on Node 18, 20, 21

ok I'm going to remove 14.x & 16.x since those won't work with this change.

**Comment by hulkish** [comment]
Ok, so tests actually passed - but I'll need to lower the minimum coverage required to 85%

**Comment by hulkish** [comment]
@andris9 says I need to sign my commits, is that really necessary?

**Comment by andris9** [comment]
You don't have to sign these commits even though it would be preferred. Merging now. Thanks.

**Pull request merged**
