### PR TITLE
Raising this PR for the documentation part.

### PR DESCRIPTION
**Pull request by sibStephen**
- If user hasn't configured the sendmail in his/her system then there must be
document statement stating, there is a sendamil configuration that needs to be done,
if he/she is a new user.

### CODE REVIEW

**Comment by andris9** [comment]
This is too specific and probably should go into the webpage docs and not into README

**Comment by sibStephen** [comment]
So should I raise a PR in documentation section for nodemailer ?

**Comment by sibStephen** [comment]
Also can you give me the repo access for documentation part ? So that I can contribute towards the documentation part ? Would be happy to help :)

**Comment by andris9** [comment]
You can find the Nodemailer webpage repo here: https://github.com/nodemailer/nodemailer-web

**Pull request closed without merging**
